---
name: Snyk Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Snyk Monitor
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --org=${{ secrets.SNYK_ORG_ID }}
